name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_html:
    git:
      url: https://github.com/KQED/flutter_html.git
      ref: allow-srcdoc-and-point-dependencies-to-kqed-repo
  flutter_html_all:
    git:
      url: https://github.com/KQED/flutter_html.git
      path: packages/flutter_html_all
      ref: allow-srcdoc-and-point-dependencies-to-kqed-repo
  flutter:
    sdk: flutter

dependency_overrides:
  flutter_html:
    git:
      url: https://github.com/KQED/flutter_html.git
      ref: allow-srcdoc-and-point-dependencies-to-kqed-repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg
